directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_111
- CKV_AWS_356
- CKV_TF_1
- CKV_AWS_94
- CKV_AWS_99