directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_TF_1
- CKV_AWS_94
- CKV_AWS_99
- CKV_AWS_108
- CKV_AWS_109
- CKV_AWS_110
- CKV_AWS_111
- CKV_AWS_356